name: "Hello Action"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Word"

runs:
  useing: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"